version: '3'
services:

  subzero:
    image: playzero/subzero:latest
    container_name: gamedao-node
    restart: always
    ports:
      - "9944:9944"
      - "30333:30333"
    user: "$UID:$GID"
    command: [
        "/usr/local/bin/subzero",
        "--name", "subzero",
        "--dev",
        "--tmp"
      ]
    environment:
      VIRTUAL_PORT: 9944
      VIRTUAL_HOST: node.beta.gamedao.co
      LETSENCRYPT_HOST: node.beta.gamedao.co
      LETSENCRYPT_EMAIL: hey@gamedao.co

  app:
    image: gamedao/app:local
    container_name: gamedao-app
    restart: always
    ports:
      - "80:80"
    environment:
      IPFS_HOST: ipfs
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: app.beta.gamedao.co
      LETSENCRYPT_HOST: app.beta.gamedao.co
      LETSENCRYPT_EMAIL: hey@gamedao.co
